use crate::parser::{CaplaType, ValidatedFunctionSignature, ValidatedParam, ValidatedReturn};
#[derive(Debug, Clone)]
pub struct SelectedFunction {
    pub sig: ValidatedFunctionSignature,
    pub export_name: String,
}

pub struct GeneratedFiles {
    pub header: String,
    pub source: String,
}

fn c_declaration(sel: &SelectedFunction) -> String {
    let ret = &sel.sig.return_type.as_c_type();
    let params: String = if sel.sig.params.is_empty() {
        "void".to_string()
    } else {
        sel.sig
            .original_params
            .iter()
            .map(|p| format!("{} {}", p.ty.as_c_type(), p.name))
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!("{} {}({})", ret, sel.sig.name, params)
}

fn certicoq_declaration(sel: &SelectedFunction) -> String {
    let tinfo = if matches!(
        sel.sig.return_type,
        ValidatedReturn::Numeric(CaplaType::F64) | ValidatedReturn::StringReturn(_)
    ) {
        Some("struct thread_info *tinfo".to_string())
    } else {
        None
    };
    let params: String = if sel.sig.params.is_empty() {
        "void".to_string()
    } else {
        tinfo
            .into_iter()
            .chain(sel.sig.params.iter().filter_map(|p| match p {
                ValidatedParam::RocqParam(p) => Some(format!("value {}", p.name)),
                ValidatedParam::StringLengthParam { .. } => None,
                ValidatedParam::StringOutputParam { .. } => None,
            }))
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!("value {}({})", sel.export_name, params)
}

pub fn generate(selections: &[SelectedFunction], header_name: &str) -> GeneratedFiles {
    let guard = header_name.to_uppercase().replace(['.', '-', ' '], "_");

    let mut h = String::new();
    h.push_str(&format!(
        "/* Auto-generated by capla_extractor. Do not edit unless necessary. */\n\
         #ifndef {guard}\n\
         #define {guard}\n\n\
         #include <stdint.h>\n\
         #include \"values.h\"\n\n\
         "
    ));

    for sel in selections {
        let decl = certicoq_declaration(sel);
        if let Some(doc) = build_doc(sel) {
            h.push_str(&doc);
        }
        h.push_str(&format!("{};\n\n", decl));
    }
    h.push_str(&format!("#endif /* {guard} */\n"));

    let mut c = String::new();
    c.push_str(
        "\
        /* Auto-generated by capla_extractor. Do not edit unless necessary. */\n\
        #include <stdint.h>\n\
        #include \"values.h\"\n\
        extern value mk_float(struct thread_info *tinfo, value my_float);\n\
        extern value prim_string_make(struct thread_info *tinfo, value bytes, value d);\n\n",
    );
    for sel in selections {
        let decl = c_declaration(sel);
        c.push_str(&format!("extern {decl};\n"));
    }
    c.push('\n');

    for sel in selections {
        let decl = certicoq_declaration(sel);
        let arg_casts = sel
            .sig
            .params
            .iter()
            .map(|p| p.into_capla())
            .collect::<Vec<_>>()
            .join(", ");
        let return_val = format!("{}({})", sel.sig.name, arg_casts);
        let final_cast = sel.sig.return_type.from_capla(return_val);
        c.push_str(&format!(
            "{decl} {{\n\
             {}\treturn {};\n\
             }}\n\n",
            sel.sig.previous_instructions(),
            final_cast
        ));
    }

    GeneratedFiles {
        header: h,
        source: c,
    }
}

fn build_doc(sel: &SelectedFunction) -> Option<String> {
    let mut lines = vec!["/**".to_string()];
    lines.push(format!(" * @brief {}", sel.export_name));
    for p in &sel.sig.params {
        match p {
            ValidatedParam::RocqParam(p) => {
                lines.push(format!(" * @param {} ({})", p.name, p.ty.as_rocq_type()))
            }
            ValidatedParam::StringLengthParam { .. } | ValidatedParam::StringOutputParam { .. } => {
            }
        }
    }
    lines.push(format!(" * @return {}", sel.sig.return_type.as_rocq_type()));
    lines.push(" */".to_string());
    Some(lines.join("\n") + "\n")
}
